---
all:
  hosts:
    10.10.10.142:
    10.10.10.157:
  vars:
    ansible_network_os: "ios"
    ansible_user: "cisco"
    ansible_password: "cisco"
    ansible_python_interpreter: "/usr/bin/env python"

    ntp_server1: "192.0.2.1"
    ntp_server2: "192.0.2.2"

