---
- name: "PLAY 1: Manage NTP config"
  hosts: "all"
  tasks:
    - name: "TASK 0: Validate NTP server IP addresses"
      assert:
        that:
          - "ntp_server1 is defined"
          - "ntp_server2 is defined"
          - "ntp_server1 | ipv4 == ntp_server1"
          - "ntp_server2 | ipv4 == ntp_server2"
        msg: "Malformed input; please check ntp_server values"

    - name: "TASK 1: Apply NTP updates"
      ios_config:
        lines:
          - "ntp authenticate"
          - "ntp logging"
          - "ntp server {{ ntp_server1 }}"
          - "ntp server {{ ntp_server2 }}"

    - name: "TASK 2: Print changes if NTP config changed"
      debug:
        var: "ntp_updates.updates"
      when: "ntp_updates.updates is defined"
